from . import stock_picking
from . import ir_attachment
from . import receiving_wood
from . import operations
from . import res_partner
from . import mrp_production
from . import res_config_settings
from . import stock_quant
from . import stock_move
